// Local-only proxy for a MiMo GGUF served by llama.cpp. No packages needed.
import {createServer} from 'node:http';
const HOST='127.0.0.1', PORT=Number(process.env.PORT||8765), MODEL=process.env.MIMO_URL||'http://127.0.0.1:18182';
const allowed=new Set(['https://jacobegarcia.github.io','http://127.0.0.1:8765','http://localhost:8765']);
function headers(req){let origin=req.headers.origin;return {'Content-Type':'application/json','Access-Control-Allow-Origin':allowed.has(origin)?origin:'http://127.0.0.1:8765','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Allow-Headers':'Content-Type','Vary':'Origin','Cache-Control':'no-store'}}
function send(res,status,body,h={}){res.writeHead(status,{'Content-Type':'application/json',...h});res.end(JSON.stringify(body))}
async function ready(){try{let r=await fetch(MODEL+'/v1/models',{signal:AbortSignal.timeout(1800)});return r.ok}catch{return false}}
function parseModel(text){let s=text.replace(/```(?:json)?|```/g,'').trim(), a=s.indexOf('{'), b=s.lastIndexOf('}'); if(a<0||b<a)throw Error('Model did not return JSON'); let obj=JSON.parse(s.slice(a,b+1));return {title:String(obj.title||'Review complete').slice(0,100),summary:String(obj.summary||'').slice(0,600),findings:(Array.isArray(obj.findings)?obj.findings:[]).slice(0,10).map(f=>({line:String(f.line||''),severity:String(f.severity||''),title:String(f.title||''),explanation:String(f.explanation||''),fix:String(f.fix||'')}))}}
function parseThreat(text){let s=text.replace(/```(?:json)?|```/g,'').trim(),a=s.indexOf('{'),b=s.lastIndexOf('}');if(a<0||b<a)throw Error('Model did not return JSON');let o=JSON.parse(s.slice(a,b+1));return {title:String(o.title||'Threat map').slice(0,100),summary:String(o.summary||'').slice(0,600),boundaries:(Array.isArray(o.boundaries)?o.boundaries:[]).slice(0,8).map(x=>(typeof x==='string'?x:(x&&typeof x==='object'?Object.entries(x).map(([k,v])=>k+': '+(typeof v==='string'?v:JSON.stringify(v))).join(' · '):String(x))).slice(0,700)),risks:(Array.isArray(o.risks)?o.risks:[]).slice(0,10).map(r=>Object.fromEntries(['asset','priority','title','path','control'].map(k=>[k,String(r[k]||'').slice(0,700)])))}}
createServer(async(req,res)=>{let h=headers(req);if(req.headers.origin&&!allowed.has(req.headers.origin)){send(res,403,{error:'Origin not allowed'},h);return}if(!['127.0.0.1','localhost'].includes(String(req.headers.host||'').split(':')[0])){send(res,403,{error:'Host not allowed'},h);return}if(req.method==='OPTIONS'){res.writeHead(204,h);res.end();return}if(req.url==='/health'&&req.method==='GET'){send(res,200,{model_ready:await ready()},h);return}if(!['/review','/threat'].includes(req.url)||req.method!=='POST'){send(res,404,{error:'Not found'},h);return}let raw='';for await(const c of req){raw+=c;if(raw.length>190000){send(res,413,{error:'Source too large'},h);return}}try{let payload=JSON.parse(raw);let {source,filename}=payload; if(req.url==='/review'&&(typeof source!=='string'||!source.trim()||source.length>180000))throw Error('Invalid source');if(req.url==='/threat' && (!payload.name||!payload.components))throw Error('Missing system details');let prompt=`Review the following file for concrete correctness, reliability and defensive security issues. Give only issues supported by the supplied code. Do not invent dependencies or runtime context. Do not execute code. Reply ONLY as JSON: {"title":"short title","summary":"short summary","findings":[{"line":"line number or range","severity":"high|medium|low","title":"short issue","explanation":"evidence and impact","fix":"specific safe change"}]}. If none, return findings: []. File: ${String(filename||'untitled').slice(0,90)}\n\n${String(source||'').slice(0,50000)}`;
if(req.url==='/threat')prompt=`Build a defensive threat model for the user's own described system. Identify trust boundaries, realistic abuse paths, and concrete mitigations. Do not assume architecture not supplied. No exploit instructions or scanning. Reply ONLY JSON: {"title":"short title","summary":"short summary","boundaries":["boundary with assets and trust change"],"risks":[{"asset":"affected asset","priority":"high|medium|low","title":"risk","path":"plausible failure path and needed conditions","control":"concrete defense"}]}. System details: ${JSON.stringify(payload).slice(0,12000)}`;let r=await fetch(MODEL+'/v1/chat/completions',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({model:process.env.MIMO_MODEL||'local-mimo',messages:[{role:'user',content:prompt}],temperature:0.2,max_tokens:2600,stream:false}),signal:AbortSignal.timeout(110000)});if(!r.ok)throw Error('Model server responded '+r.status);let j=await r.json();send(res,200,req.url==='/threat'?parseThreat(j.choices?.[0]?.message?.content||''):parseModel(j.choices?.[0]?.message?.content||''),h)}catch(e){send(res,502,{error:String(e.message).slice(0,250)},h)}}).listen(PORT,HOST,()=>console.log(`PATCHROOM bridge at http://${HOST}:${PORT}; model ${MODEL}`));
